---
dps:
  s1:
    dp_id: 0x1
    hardware: "Open vSwitch"
    interfaces:
      1:
        name: "h1"
        description: "host1"
        native_vlan: 100
      2:
        name: "h2"
        description: "host2"
        native_vlan: 100
      3:
        name: "h3"
        description: "host3"
        native_vlan: 100
      4:
        name: "h4"
        description: "host4"
        native_vlan: 100
      5:
        name: "h5"
        description: "host5"
        native_vlan: 100

vlans:
  100:
    name: "network"
    description: "Main network"
    faucet_mac: "0e:00:00:00:10:01"
    faucet_vips:
      - '10.0.0.254/24'
